name: open-integration-engine

services:
  ubuntu-jdk:
    image: openintegrationengine/engine
    build:
      dockerfile: Dockerfile
      target: ubuntu
      context: .
      args: &jdk-args
        UBUNTU_TAG: ${UBUNTU_JDK_TAG:?}
        ALPINE_TAG: ${ALPINE_JDK_TAG:?}
        OIE_RELEASE_VERSION: ${OIE_RELEASE_VERSION:?}
        OIE_RELEASE_URL: ${OIE_RELEASE_URL:?}
      platforms: &platforms
      - linux/amd64
#      - linux/arm64
      tags:
        - openintegrationengine/engine:latest-ubuntu-jdk
        - openintegrationengine/engine:${OIE_RELEASE_VERSION?:}-ubuntu-jdk

  ubuntu-jre:
    image: openintegrationengine/engine
    build:
      dockerfile: Dockerfile
      target: ubuntu
      context: .
      args: &jre-tags
        UBUNTU_TAG: ${UBUNTU_JRE_TAG:?}
        ALPINE_TAG: ${ALPINE_JRE_TAG:?}
        OIE_RELEASE_VERSION: ${OIE_RELEASE_VERSION:?}
        OIE_RELEASE_URL: ${OIE_RELEASE_URL:?}
      platforms: *platforms
      tags:
        - openintegrationengine/engine:latest-ubuntu
        - openintegrationengine/engine:latest-ubuntu-jre
        - openintegrationengine/engine:${OIE_RELEASE_VERSION?:}-ubuntu
        - openintegrationengine/engine:${OIE_RELEASE_VERSION?:}-ubuntu-jre

  alpine-jdk:
    image: openintegrationengine/engine
    build:
      dockerfile: Dockerfile
      target: alpine
      context: .
      args: *jdk-args
      platforms: *platforms
      tags:
        - openintegrationengine/engine:latest-alpine-jdk
        - openintegrationengine/engine:${OIE_RELEASE_VERSION?:}-alpine-jre

  alpine-jre:
    image: openintegrationengine/engine
    build:
      dockerfile: Dockerfile
      target: alpine
      context: .
      args: *jre-tags
      platforms: *platforms
      tags:
        - openintegrationengine/engine:latest
        - openintegrationengine/engine:latest-alpine
        - openintegrationengine/engine:latest-alpine-jre
        - openintegrationengine/engine:${OIE_RELEASE_VERSION?:}-alpine
        - openintegrationengine/engine:${OIE_RELEASE_VERSION?:}-alpine-jre
